#!/bin/bash

interface=wlan0
user=corobot

corobot_stamp () {
    echo "[`date +"%Y/%m/%d %T"`] $1"
}

setup_file=/opt/ros/fuerte/setup.bash

corobot_stamp "Starting using setup file $setup_file"
source /opt/ros/fuerte/setup.bash

corobot_stamp "Using interface $interface"
export ROS_IP=`ifconfig $interface | grep -o 'inet addr:[^ ]*' | cut -d: -f2`

if [ "$ROS_IP" = "" ]; then
    corobot_stamp "Can't run with empty ROS_IP."
    exit 1
else
    corobot_stamp "Setting ROS_IP=$ROS_IP"
fi

setuidgid $user roslaunch corobot_bringup kinect.launch
