#!/bin/bash

corobot_stamp () {
    echo "[`date +"%Y/%m/%d %T"`] $1"
}

setup_file=/opt/ros/fuerte/setup.bash

corobot_stamp "Stopping using setup file $setup_file"
source $setup_file

for i in $(rosnode list); do
    rosnode kill $i;
done

killall roslaunch
