/* Auto-generated by genmsg_cpp for file /home/spyder/corobot_ws/src/corobots/face_recognition/msg/FaceRecognitionActionGoal.msg */
#ifndef FACE_RECOGNITION_MESSAGE_FACERECOGNITIONACTIONGOAL_H
#define FACE_RECOGNITION_MESSAGE_FACERECOGNITIONACTIONGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "actionlib_msgs/GoalID.h"
#include "face_recognition/FaceRecognitionGoal.h"

namespace face_recognition
{
template <class ContainerAllocator>
struct FaceRecognitionActionGoal_ {
  typedef FaceRecognitionActionGoal_<ContainerAllocator> Type;

  FaceRecognitionActionGoal_()
  : header()
  , goal_id()
  , goal()
  {
  }

  FaceRecognitionActionGoal_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , goal_id(_alloc)
  , goal(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
   ::actionlib_msgs::GoalID_<ContainerAllocator>  goal_id;

  typedef  ::face_recognition::FaceRecognitionGoal_<ContainerAllocator>  _goal_type;
   ::face_recognition::FaceRecognitionGoal_<ContainerAllocator>  goal;


  typedef boost::shared_ptr< ::face_recognition::FaceRecognitionActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::face_recognition::FaceRecognitionActionGoal_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct FaceRecognitionActionGoal
typedef  ::face_recognition::FaceRecognitionActionGoal_<std::allocator<void> > FaceRecognitionActionGoal;

typedef boost::shared_ptr< ::face_recognition::FaceRecognitionActionGoal> FaceRecognitionActionGoalPtr;
typedef boost::shared_ptr< ::face_recognition::FaceRecognitionActionGoal const> FaceRecognitionActionGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::face_recognition::FaceRecognitionActionGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::face_recognition::FaceRecognitionActionGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace face_recognition

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::face_recognition::FaceRecognitionActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::face_recognition::FaceRecognitionActionGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::face_recognition::FaceRecognitionActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4b046671794585c575f6b529dd4decb9";
  }

  static const char* value(const  ::face_recognition::FaceRecognitionActionGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4b046671794585c5ULL;
  static const uint64_t static_value2 = 0x75f6b529dd4decb9ULL;
};

template<class ContainerAllocator>
struct DataType< ::face_recognition::FaceRecognitionActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "face_recognition/FaceRecognitionActionGoal";
  }

  static const char* value(const  ::face_recognition::FaceRecognitionActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::face_recognition::FaceRecognitionActionGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
FaceRecognitionGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: face_recognition/FaceRecognitionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
uint8   order_id \n\
string  order_argument\n\
\n\
";
  }

  static const char* value(const  ::face_recognition::FaceRecognitionActionGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::face_recognition::FaceRecognitionActionGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::face_recognition::FaceRecognitionActionGoal_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::face_recognition::FaceRecognitionActionGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.goal_id);
    stream.next(m.goal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct FaceRecognitionActionGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::face_recognition::FaceRecognitionActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::face_recognition::FaceRecognitionActionGoal_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
s << std::endl;
    Printer< ::face_recognition::FaceRecognitionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};


} // namespace message_operations
} // namespace ros

#endif // FACE_RECOGNITION_MESSAGE_FACERECOGNITIONACTIONGOAL_H

